# This is an example docker-compose.yml that shows you how to run the project locally
# It is not meant to be used as is in production
version: "3.7"

services:
  demo:
    build:
      context: .
      args:
        # Required
        PUBLIC_URL: ${PUBLIC_URL}
        REACT_APP_EBSI_ENV: ${REACT_APP_EBSI_ENV}
        # Optional
        REACT_APP_SELF_SOVEREIGN_IDENTITY_URL: ${REACT_APP_SELF_SOVEREIGN_IDENTITY_URL}
        REACT_APP_NOTARISATION_URL: ${REACT_APP_NOTARISATION_URL}
        REACT_APP_DIPLOMA_BACHELOR_URL: ${REACT_APP_DIPLOMA_BACHELOR_URL}
        REACT_APP_DIPLOMA_MASTER_URL: ${REACT_APP_DIPLOMA_MASTER_URL}
        REACT_APP_WALLET_WEB_CLIENT_URL: ${REACT_APP_WALLET_WEB_CLIENT_URL}
        REACT_APP_TRUSTED_DATA_SHARING_URL: ${REACT_APP_TRUSTED_DATA_SHARING_URL}
    ports:
      - "8080:8080"
